[package]
name = "sysdig-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["full"] }
tower-lsp = "0.20.0"
tower-service = "0.3.3"
